### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by WeeCoopTech** [kristerkari/react-native-svg-transformer#104]
Hello, 
I've followed the instructions and also those of react-native-svg-transformer but I get this : 

_`transform[stderr]: [BABEL] Note: The code generator has deoptimised the styling of C:\Users\Administrateur\Desktop\unknown as it exceeds the max of 500KB.`_

Do you have any idea of how I can make it works ? Thanks a lot

**Comment by kristerkari** [comment]
@WeeCoopTech is possible for you to upload your project somewhere where I can have a look at it? Otherwise it's very difficult to say anything about the error.

**Comment by WeeCoopTech** [comment]
Hello, thank you for answering quickly ! I found the problem, it was the extension, I did the mistake of not changing svg in svgx. I'm sorry.

**Comment by kristerkari** [comment]
No worries!
