### ISSUE TITLE
Problem with Jest mock

### ISSUE THREAD

**Issue by dbenfouzari** [kristerkari/react-native-svg-transformer#106]
I'm trying to get it to work with Jest.

So I did
```js
// __mocks__/svgMocks.js
module.exports = 'SvgMock';
module.exports.ReactComponent = 'SvgMock';

```

And my Jest config is
```json
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/jest-setup.js"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "moduleNameMapper": {
      "\\.svg": "<rootDir>/__mocks__/svgMock.js"
    }
  },
```

With that in place, I get a Jest error 

    Configuration error:
    
    Could not locate module ./step1.svg mapped as:
    /Users/dbenfouzari/Projects/xxxx/__mocks__/svgMock.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/\.svg/": "/Users/dbenfouzari/Projects/xxxx/__mocks__/svgMock.js"
      },
      "resolver": undefined
    }

**Comment by dbenfouzari** [comment]
Hm... That's better when I name it correctly `svgMocks.js`
Good job

**Comment by Thorugoh** [comment]
Obrigado cara, seu problema era a minha solução tu és um baita.

**Comment by BlagojeV93** [comment]
I keep getting the exact same error, even though I double checked the imports and file naming, and everything is in order. I wonder if anyone has encountered this issue lately?

**Comment by AhmedAbuelenin** [comment]
> I keep getting the exact same error, even though I double checked the imports and file naming, and everything is in order. I wonder if anyone has encountered this issue lately?

// jest.config.js
{
 ...,
  moduleNameMapper: {
    '\\.svg$': '<rootDir>/__mocks__/svgMock.js' // add <rootDir> in your path
  }
}

[Thanks to ](https://github.com/kristerkari/react-native-svg-transformer/issues/163)
