### ISSUE TITLE
Unable to resolve module - without using Expo

### ISSUE THREAD

**Issue by jpetera54** [kristerkari/react-native-svg-transformer#115]
Hello, I've been trying to use this library, but I got stuck at this error while importing. 

`import CatFoods from '@assets/svg/cat-foods.svg';`

Error:
`Unable to resolve module '../../assets/svg/cat-foods.svg'`

I am using: `"react-native": "0.63.4"`, `"react-native-svg": "^12.1.0"`. Also, I use typescript and I have Jest installed, but I haven't written any tests. I am not using Expo. React native svg library works properly. I have created `declarations.d.ts` file and linting works correctly.

Content of my `metro.config.js` file. 
```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
      experimentalImportSupport: false,
      inlineRequires: false
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
```

**Comment by ksturner** [comment]
I hit this error too and found that including the following `packagerOpts` section in my `app.json` file worked to include those files. 

```
{
  "expo": {
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": ["ts", "tsx", "js", "jsx", "json", "wasm", "svg"]
    }
  }
}
```

**Comment by kristerkari** [comment]
Hey @jpetera54! Can you upload your project somewhere where I could I have a look at it. From your description it's very difficult to know if for example the problem is in the config or just the path being wrong.

**Comment by jpetera54** [comment]
Hey. 
I actually opt out and started using fonts instead of this library, as I needed a quick solution. I am not even sure that I could reproduce this bug. 
Some possible lead though is that I am developing on Windows. And as that's not quite a norm I often run into problems related to my operation system. Maybe something with \ being used instead of / in paths? 
I am just spinning ideas. Sorry that I cannot be any more helpfull. Thank you for your response. ;)

**Comment by Sandeeprao69** [comment]
Hi,
I am facing same issu, is there any way to resolve this?
