### ISSUE TITLE
the config breaks icons in @expo/vector-icons  in EXPO 40

### ISSUE THREAD

**Issue by gasolin** [kristerkari/react-native-svg-transformer#116]
apply config https://github.com/kristerkari/react-native-svg-transformer/blob/master/README.md#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

in Expo 39 looks fine, but in Expo 40 it breaks the icons in @expo/vector-icons with
`Unrecognized font family 'ionicons'`  error

https://github.com/expo/vector-icons/issues/152

remove `sourceExts` make @expo/vector-icons import works again but then the app can't recognize `.svg` files ....

Change the `sourceExts` to the same list as app.json fixed this issue

```
sourceExts: [
        'expo.ts',
        'expo.tsx',
        'expo.js',
        'expo.jsx',
        'ts',
        'tsx',
        'js',
        'jsx',
        'json',
        'wasm',
        'svg'
      ],
```

**Comment by gasolin** [comment]
as https://docs.expo.io/guides/customizing-metro/ mentioned, should import `@expo/metro-config` instead of `metro-config` in expo 40

```
const { getDefaultConfig } = require('@expo/metro-config')

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig(__dirname)
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  }
})()

```

**Comment by kiwina** [comment]
this works for me on expo
`
const { getDefaultConfig } = require("@expo/metro-config")
const defaultConfig = getDefaultConfig(__dirname)
const assetExt = defaultConfig.resolver.assetExts.filter((ext) => ext !== 'svg')
module.exports = {
  transformer: {
    babelTransformerPath: require.resolve("react-native-svg-transformer"),
  },
  resolver: {
    assetExts: [...assetExt],
    sourceExts: [...defaultConfig.resolver.sourceExts, "svg"],
  },
}
`
