### ISSUE TITLE
Problems with react-native-svg-transformer and typescript

### ISSUE THREAD

**Issue by Oscar-Silva** [kristerkari/react-native-svg-transformer#125]
I decided to add typescript in a existing project and have a issue when a i works with import of .svg like a this
`import Icon from "../../../assets/Icon.svg";`

i tried configure metro.config.js
```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"],
    },
  };
})();
```

and add a declarations file

```
declare module "*.svg" {
  import React from "react";
  import { SvgProps } from "react-native-svg";

  const content: React.FC<SvgProps>;
  export default content;
}

```

but it's not work for me, and i get the error

in terminal

![image](https://user-images.githubusercontent.com/46907491/108073906-579fa000-7047-11eb-8ce7-a5ab27a64bea.png)

in the phone: 

![image](https://user-images.githubusercontent.com/46907491/108074195-b06f3880-7047-11eb-8bde-c0879c2b289b.png)

**Comment by edwardigates** [comment]
At what level did you add the declarations.d.ts file?

**Comment by Oscar-Silva** [comment]
> At what level did you add the declarations.d.ts file?

i tried in differents path, but at the momento, declarations.d.ts file is in the root of project

**Comment by ithustle** [comment]
@Oscar-Silva , what was the solution?
