### ISSUE TITLE
React Native 0.64

### ISSUE THREAD

**Issue by teamzz111** [kristerkari/react-native-svg-transformer#130]
Running 0.64 with Android I've the following error:

Validation Warning:

  Unknown option "t" with value {"babelTransformerPath": "/Users/andreslargo/Develop/chamba-app/node_modules/react-native-svg-transformer/index.js", "getTransformOptions": [Function getTransformOptions]} was found.
  This is probably a typing mistake. Fixing it will remove this message.

warning: the transform cache was reset.
the transform cache was reset.

                    Welcome to Metro!
              Fast - Scalable - Integrated

> Task :app:bundleReleaseJsAndAssets
error SyntaxError: /Users/andreslargo/Develop/chamba-app/src/assets/images/MainHome/appleLogo.svg: Unexpected token (1:1)
SyntaxError: /Users/andreslargo/Develop/chamba-app/src/assets/images/MainHome/appleLogo.svg: Unexpected token (1:1)

On 0.63 works as well.

**Comment by kristerkari** [comment]
I haven't tried the library with 0.64 yet, but I'll try it out later.

**Comment by gabrielmoncea** [comment]
I've tried in multiple projects and this library works fine. You should refollow the docs
