### ISSUE TITLE
Unhandled Rejection (InvalidCharacterError): Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/....svg') is not a valid name.

### ISSUE THREAD

**Issue by lucassouza16** [kristerkari/react-native-svg-transformer#135]
src/index.js

```
import React from 'react'
import { View } from 'react-native'
import User from '../assets/svg/User.svg'

const Index = () => {
    return (
       <View>
           <User width={40} height={40} fill='red'/>
       </View>
    )
}

export default Index
```

metro.config.js

```
const { getDefaultConfig } = require("@expo/metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig(__dirname);
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
```

babel.config.js

```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
```

declarations.d.ts

```
declare module "*.svg" {
    import React from 'react';
    import { SvgProps } from "react-native-svg";
    const content: React.FC<SvgProps>;
    export default content;
  }
```

.svgrrc

```
{
  "replaceAttrValues": {
    "#000": "{props.fill}"
  }
}
```

app.json

```
{
  "expo": {
    "name": "Project",
    "slug": "Project",
    "version": "3.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#007B5E"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "com.ico.app.teste",
      "googleServicesFile": "./google-services.json",
      "useNextNotificationsApi": true,
      "versionCode": 100,
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ]
    },
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "expo.ts",
        "expo.tsx",
        "expo.js",
        "expo.jsx",
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "wasm",
        "svg"
      ]
    }
  }
}
```

package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/montserrat": "^0.1.0",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/viewpager": "5.0.11",
    "@react-navigation/bottom-tabs": "^5.9.0",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",
    "@types/styled-components-react-native": "^5.1.1",
    "axios": "^0.19.2",
    "expo": "~41.0.1",
    "expo-cli": "^3.23.1",
    "expo-facebook": "~11.0.5",
    "expo-font": "~9.1.0",
    "expo-linear-gradient": "~9.1.0",
    "expo-linking": "~2.2.3",
    "expo-location": "lucassouza16/expo-location#latest",
    "expo-notifications": "~0.11.6",
    "expo-status-bar": "~1.0.4",
    "git": "^0.1.5",
    "global": "^4.4.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-masked-text": "^1.13.0",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.2.3",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/jest": "^26.0.21",
    "@types/react": "^17.0.3",
    "@types/react-native": "^0.64.0",
    "@types/react-test-renderer": "^17.0.1",
    "babel-preset-expo": "^8.3.0",
    "typescript": "^4.2.3"
  },
  "private": true
}

```

Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\lucas\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Comment by lucassouza16** [comment]
I created a temporary solution to the problem, whoever wants to try it feels free.

https://github.com/lucassouza16/react-native-svg-transformer-fix-expo

**Comment by knavels** [comment]
Hello any news on this issue?

**Comment by cvburgess** [comment]
Any way we can get @lucassouza16's work or another solution into a release?

**Comment by lucassouza16** [comment]
> Any way we can get @lucassouza16's work or another solution into a release?

It was a temporary solution that I created for a project that was urgent to be completed, and I found it interesting to share, but little by little I'm not using this library to render svgs, and replacing it in the project with the conventional way, I thought that at this point this problem had already been resolved, but it seems that the author abandoned the project.

**Comment by mattgabor** [comment]
Hi just wanted to check on the status of this - @kristerkari is there a way we can get this fix merged in? It's unusable on react-native-web without this fix.

**Comment by kristerkari** [comment]
@mattgabor just open a Pull Request with the fix, and I can have a look at it.

**Comment by mattgabor** [comment]
@lucassouza16 do you mind putting up a PR with the changes you made in react-native-svg-transformer-fix-expo? I'm also happy to make the PR but don't know exactly what was changed since your repo is not a fork.

**Comment by lucassouza16** [comment]
> @lucassouza16 do you mind putting up a PR with the changes you made in react-native-svg-transformer-fix-expo? I'm also happy to make the PR but don't know exactly what was changed since your repo is not a fork.

I don't think that in the short term my solution is interesting to be implemented as a final solution, but temporary, as I have little knowledge about webpack, I did it in a rough way to temporarily solve the problem in a project that had an urgent need to be delivered, using a loader that replaces imports referring to svg files with a component call on all files, but I predict that in a project with very dense code files this solution can lead to problems, so much so that I made it so that it could be easily replicated by a better solution.

**Comment by kristerkari** [comment]
I would definitely be interested in fixing the support for Expo web, but I'm not sure how.

I have created a Webpack config that works with the normal React Native, but I have no idea of how to configure it for Expo.

Here's a reference for normal RN in case it helps:
https://github.com/kristerkari/react-native-svg-example/blob/master/webpack.config.js

**Comment by lucassouza16** [comment]
> @ lucassouza16 você se importa em colocar um PR com as mudanças que você fez em react-native-svg-transformer-fix-expo? Também estou feliz por fazer o PR, mas não sei exatamente o que foi alterado, já que seu repo não é um fork.

Another solution I developed was this one, although not the most correct either, was to add this code, I added it before the call `registerRootComponent(App);` in the index.js file, I think it's much less invasive than the previous one:

```
if (Platform.OS == 'web') {
    
    const originalCreateElement = document.createElement;

    const updateAttributesFromChildrens = (props, el) => {

        props.forEach(attrb => {

            el.querySelectorAll('*').forEach(ch => {

                if ((/^width|height$/).test(attrb) && ch.tagName != 'svg') return;

                if (ch.hasAttribute(attrb)) {
                    ch.setAttribute(attrb, el.getAttribute(attrb));
                }
            });
        });
    }

    document.createElement = (tag) => {

        if ((/[\/\.\:]/).test(tag)) {
            
            const newNode = document.createElement('div');

            let observer = new MutationObserver(function (mutations) {
                updateAttributesFromChildrens(mutations.map(m => m.attributeName), newNode);
            });

            observer.observe(newNode, { attributes: true });

            fetch(tag).then(e => e.text()).then(inner => {
                newNode.innerHTML = inner;
                updateAttributesFromChildrens(Array.from(newNode.attributes).map(e => e.nodeName), newNode);
            });

            return newNode;
        } else {
            return originalCreateElement.call(document, tag);
        }
    }
}
```

The error occurs, because when importing the file with svg extension into Expo Web, it will bring it in the form of a url, or in base64 format, the document.createElement function receives as parameter the name of the html tag to be created, and not a url, then the error occurs, then it replaces the original function with another changed one, and as I said, I can't find the correct way to solve the problem, but it was the simplest and safest I found.

**Comment by lucassouza16** [comment]
> Eu definitivamente estaria interessado em consertar o suporte para Expo web, mas não tenho certeza de como.
> 
> Eu criei uma configuração do Webpack que funciona com o React Native normal, mas não tenho ideia de como configurá-lo para Expo.
> 
> Aqui está uma referência para RN normal, caso ajude: https://github.com/kristerkari/react-native-svg-example/blob/master/webpack.config.js



> @mattgabor basta abrir um Pull Request com a correção e posso dar uma olhada nele.

I forked the dependency and applied a solution proposal, if I find it interesting as a final solution:
https://github.com/lucassouza16/react-native-svg-transformer

**Comment by lucassouza16** [comment]
> @mattgabor just open a Pull Request with the fix, and I can have a look at it.

I forked the dependency and applied a solution proposal, if I find it interesting as a final solution:
https://github.com/lucassouza16/react-native-svg-transformer

**Comment by kristerkari** [comment]
@lucassouza16 Thanks! I see that you added a README entry to configure Webpack for Expo. What I was wondering is that could it simply use `@svgr/webpack` (https://www.npmjs.com/package/@svgr/webpack) as the loader for SVG images instead of adding a custom loader?

**Comment by lucassouza16** [comment]
> @lucassouza16 Thanks! I see that you added a README entry to configure Webpack for Expo. What I was wondering is that could it simply use `@svgr/webpack` (https://www.npmjs.com/package/@svgr/webpack) as the loader for SVG images instead of adding a custom loader?

Using this loader was a solution I tried before, and despite the svg being rendered I couldn't change properties like width, height and fill, so I chose to create another shape, I don't have enough knowledge to create a better solution, as my knowledge about these technologies is still very superficial.

**Comment by kristerkari** [comment]
> Using this loader was a solution I tried before, and despite the svg being rendered I couldn't change properties like width, height and fill, so I chose to create another shape

Oh, I see. Well I'll try it out and report back to you :)

**Comment by kristerkari** [comment]
@lucassouza16 @cvburgess @mattgabor 

I had a look at adding the Webpack config for Expo, and I managed to find a solution from the Expo repo (https://github.com/expo/expo/issues/6660#issuecomment-667991626) that is kind of working. 

The only bigger problem that I ran into is that the newest versions of SVGR only support Webpack v5, but Expo is still using Webpack v4. I managed to fix that in hacky way by using an older 5.5.0 version of `@svgr/webpack`, but forcing the other `@svgr/*` packages to be version 6.1.2.

If you want to have a look at an example, you can try out locally the changes here:
https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files

**Comment by lucassouza16** [comment]
> @ lucassouza16 @cvburgess @mattgabor
> 
> Dei uma olhada na adição da configuração do Webpack para Expo e consegui encontrar uma solução no repo da Expo ( [expo / expo # 6660 (comentário)](https://github.com/expo/expo/issues/6660#issuecomment-667991626) ) que está funcionando.
> 
> O único problema maior que encontrei é que as versões mais recentes do SVGR suportam apenas o Webpack v5, mas a Expo ainda usa o Webpack v4. Consegui consertar isso de forma hacky usando uma versão 5.5.0 mais antiga do `@svgr/webpack`, mas forçando os outros `@svgr/*`pacotes a serem a versão 6.1.2.
> 
> Se você quiser dar uma olhada em um exemplo, pode experimentar localmente as mudanças aqui: https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files

Didn't know that, I'll try it next time, thanks!

**Comment by mattgabor** [comment]
> @lucassouza16 @cvburgess @mattgabor
> 
> I had a look at adding the Webpack config for Expo, and I managed to find a solution from the Expo repo ([expo/expo#6660 (comment)](https://github.com/expo/expo/issues/6660#issuecomment-667991626)) that is kind of working.
> 
> The only bigger problem that I ran into is that the newest versions of SVGR only support Webpack v5, but Expo is still using Webpack v4. I managed to fix that in hacky way by using an older 5.5.0 version of `@svgr/webpack`, but forcing the other `@svgr/*` packages to be version 6.1.2.
> 
> If you want to have a look at an example, you can try out locally the changes here: https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files

sounds good, I won't be able to try it out until Monday but the PR looks good to me!

**Comment by lucassouza16** [comment]
> @lucassouza16 @cvburgess @mattgabor
> 
> I had a look at adding the Webpack config for Expo, and I managed to find a solution from the Expo repo ([expo/expo#6660 (comment)](https://github.com/expo/expo/issues/6660#issuecomment-667991626)) that is kind of working.
> 
> The only bigger problem that I ran into is that the newest versions of SVGR only support Webpack v5, but Expo is still using Webpack v4. I managed to fix that in hacky way by using an older 5.5.0 version of `@svgr/webpack`, but forcing the other `@svgr/*` packages to be version 6.1.2.
> 
> If you want to have a look at an example, you can try out locally the changes here: https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files

The solution you proposed worked perfectly, thank you very much, I only had to make some updates to web.config.js, because the svg viewBox was removed and the size was disproportionate.

```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);

    config.module.rules.forEach((rule) => {
        if (rule.oneOf) {
            rule.oneOf.unshift({
                test: /\.svg$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: require.resolve("@svgr/webpack"),
                        options: {
                            svgoConfig: {
                                "plugins": [
                                    { name: "removeDoctype", active: true },
                                    { name: "removeXMLProcInst", active: true },
                                    { name: "removeComments", active: true },
                                    { name: "removeMetadata", active: true },
                                    { name: "removeXMLNS", active: true },
                                    { name: "removeEditorsNSData", active: true },
                                    { name: "cleanupAttrs", active: true },
                                    { name: "inlineStyles", active: true },
                                    { name: "minifyStyles", active: true },
                                    { name: "convertStyleToAttrs", active: true },
                                    { name: "cleanupIDs", active: true },
                                    { name: "removeRasterImages", active: true },
                                    { name: "removeUselessDefs", active: true },
                                    { name: "cleanupNumericValues", active: true },
                                    { name: "cleanupListOfValues", active: true },
                                    { name: "convertColors", active: true },
                                    { name: "removeUnknownsAndDefaults", active: true },
                                    { name: "removeNonInheritableGroupAttrs", active: true },
                                    { name: "removeUselessStrokeAndFill", active: true },
                                    { name: "removeViewBox", active: false },
                                    { name: "cleanupEnableBackground", active: true },
                                    { name: "removeHiddenElems", active: true },
                                    { name: "removeEmptyText", active: true },
                                    { name: "convertShapeToPath", active: true },
                                    { name: "moveElemsAttrsToGroup", active: true },
                                    { name: "moveGroupAttrsToElems", active: true },
                                    { name: "collapseGroups", active: true },
                                    { name: "convertPathData", active: true },
                                    { name: "convertEllipseToCircle", active: true },
                                    { name: "convertTransform", active: true },
                                    { name: "removeEmptyAttrs", active: true },
                                    { name: "removeEmptyContainers", active: true },
                                    { name: "mergePaths", active: true },
                                    { name: "removeUnusedNS", active: true },
                                    { name: "reusePaths", active: true },
                                    { name: "sortAttrs", active: true },
                                    { name: "sortDefsChildren", active: true },
                                    { name: "removeTitle", active: true },
                                    { name: "removeDesc", active: true },
                                    { name: "removeDimensions", active: false },
                                    { name: "removeStyleElement", active: false },
                                    { name: "removeScriptElement", active: false }
                                ]
                            },
                            inlineStyles: {
                                onlyMatchedOnce: false,
                            },
                            removeDimensions: false,
                            removeUnknownsAndDefaults: false,
                            convertColors: false,
                        },
                    },
                ],
            });
        }
    });

    return config;
};
```

**Comment by mattgabor** [comment]
I wasn't able to test it since when I pull the branch I get `Failed to construct transformer:  .../react-native-svg-transformer/node_modules/expo/AppEntry.js:1`

But if it fixes the issue and has @lucassouza16 changes above then I'd love to get it merged so we can start using this library again!

**Comment by lucassouza16** [comment]
> Não consegui testar pois quando puxo o galho eu recebo `Failed to construct transformer: .../react-native-svg-transformer/node_modules/expo/AppEntry.js:1`
> 
> Mas se resolver o problema e tiver @lucassouza16 alterações acima, adoraria mesclar para que possamos começar a usar essa biblioteca novamente!

**Comment by lucassouza16** [comment]
> I wasn't able to test it since when I pull the branch I get `Failed to construct transformer: .../react-native-svg-transformer/node_modules/expo/AppEntry.js:1`
> 
> But if it fixes the issue and has @lucassouza16 changes above then I'd love to get it merged so we can start using this library again!

I believe that this is no longer a library error, but the Expo version or cache, I ran my application in Web, in the Android emulator and in the iOS simulator using the latest version of the lib and the solution that the author suggested, and not gave no problem, my sdk is 39.

**Comment by lucassouza16** [comment]
> I wasn't able to test it since when I pull the branch I get `Failed to construct transformer: .../react-native-svg-transformer/node_modules/expo/AppEntry.js:1`
> 
> But if it fixes the issue and has @lucassouza16 changes above then I'd love to get it merged so we can start using this library again!

You can try to run the cache clearing procedures and the problem will probably be resolved.
