### ISSUE TITLE
Does not work with react Native 0.59.x

### ISSUE THREAD

**Issue by Thioby** [kristerkari/react-native-svg-transformer#14]
I just grabbed your example app and upgraded RN to version 0.59.2.

Application does not work at all either on IOS and Android.
![Screenshot_1554058909](https://user-images.githubusercontent.com/8046733/55293621-abc01d80-53f8-11e9-895f-131319dce016.png)

### Dependencies:

    "react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-svg": "^9.3.5",
    "react-native-svg-transformer": "^0.12.1",

**Comment by kristerkari** [comment]
Thanks!

I created a fresh 0.59.2 and added `react-native-svg` and `react-native-svg-transfomer`. Everything seems to be working fine, so it might be that you have something wrong in your configuration files.

Please see the example project that I uploaded and check your `metro.config.js`:
https://github.com/kristerkari/react-native-0.59-svg-example/blob/master/metro.config.js

**Comment by Thioby** [comment]
Thanks, problem was with `metro.config.js`

I did:
`const { getDefaultConfig } = require("metro-config");
module.exports = (async () => {
    const {
        resolver: { sourceExts, assetExts }
    } = await getDefaultConfig();
    return {
        transformer: {
            babelTransformerPath: require.resolve("react-native-svg-transformer")
        },
        resolver: {
            assetExts: assetExts.filter(ext => ext !== "svg"),
            sourceExts: [...sourceExts, "svg"]
        }
    };
})();

module.exports = {
    transformer: {
        getTransformOptions: async () => ({
            transform: {
                experimentalImportSupport: false,
                inlineRequires: false,
            },
        }),
    },
};
`

instead of:
`const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
    const {
        resolver: { sourceExts, assetExts }
    } = await getDefaultConfig();
    return {
        transformer: {
            getTransformOptions: async () => ({
                transform: {
                    experimentalImportSupport: false,
                    inlineRequires: false
                }
            }),
            babelTransformerPath: require.resolve("react-native-svg-transformer")
        },
        resolver: {
            assetExts: assetExts.filter(ext => ext !== "svg"),
            sourceExts: [...sourceExts, "svg"]
        }
    };
})();`

**Comment by kristerkari** [comment]
Oh yeah I need to change the README to say that you need to merge the config with the existing one, not only add the code.

Thanks!
