### ISSUE TITLE
Usage with Jest

### ISSUE THREAD

**Issue by lguardado** [kristerkari/react-native-svg-transformer#144]
Hi!
I've configured my project following the [docs](https://github.com/kristerkari/react-native-svg-transformer#usage-with-jest) and I still can't get the tests working. I'm using `react-native-testing-library`
I'm trying to test just rendering a simple component and I get an error in the following line.

`  > 71 |   LOGO: (height, width) => <Logo width={width} height={height} />,` saying: 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `Login`.
```

That screen is just using a logo imported like this:
`import Logo from 'assets/contents/logos/Logo.svg';`
and used like this:
`<Logo width={150} height={150} />`
I tried putting it just like that in the component just in case something was wrong with the function above

Any ideas of what I'm missing? 
I've read a lot of issues here and in other sites and I can't get it to work. 
If I remove the svg from the component everything works.

Thanks in advance!

**Comment by kristerkari** [comment]
Hmm.. really difficult to say, but my guess is that either the mock is not loaded, or then the contents of the mock file need to be updated for newer React versions.

**Comment by lguardado** [comment]
@kristerkari thanks for the answer! If you mean the `__mocks__/svgMock.js` file, I had the same feeling.... I tried putting it in  `src/__mocks__` folder as well as in the root folder just in case, but the result was the same...

**Comment by lguardado** [comment]
update: this is even more weird... I saw a warning now saying I should keep just one of those files so I kept the one in the root and started working just fine! so, I'll close this issue!

Thanks again @kristerkari for the help!

**Comment by kristerkari** [comment]
@lguardado  good that you got it to work! Maybe some will have the same issue and find this Github issue useful :)

**Comment by nguyenhoanglam** [comment]
@lguardado I've the same issue. Could you give me your mock configuration, please?
