### ISSUE TITLE
Does not work with customized project root

### ISSUE THREAD

**Issue by AnimaSA** [kristerkari/react-native-svg-transformer#15]
Hiya, I have a RN 0.59.2 project with config that looks like this:

```
const path = require("path");

const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();

  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"],

      extraNodeModules: {
        shared: path.resolve(__dirname, "../shared")
      }
    },
    // Move the project root up a level so we can access /shared, otherwise the packager can't access those assets.
    projectRoot: path.resolve(__dirname, "../")
  };
})();
```
I'm seeing the same issue from #14, but as far as I can tell the only difference between our configs is the moved project root and extra node module. Any ideas?

Dependencies:
```
"react": "16.8.3",
"react-native": "^0.59.2",
"react-native-svg": "^9.3.7",
"react-native-svg-transformer": "^0.12.1",
```

**Comment by leonardomarciano** [comment]
+1

**Comment by kristerkari** [comment]
Hmm... I'm not sure what the problem might be. I guess that I just need to try the same config to debug this.

**Comment by AnimaSA** [comment]
Following up on this, I was running my packager with `react-native start`. As it turns out, RNCLI does not care about metro.config.js when you run it this way. Mind boggling.

**Comment by AshwinMekala** [comment]
> Following up on this, I was running my packager with `react-native start`. As it turns out, RNCLI does not care about metro.config.js when you run it this way. Mind boggling.
> 
> Edit: Unless you pass --config metro.config.js
> Then it'll load. Brilliant.

@kristerkari we should add this line "react-native start --config metro.config.js" to README for more clarity.

**Comment by kristerkari** [comment]
@AshwinMekala I'm trying to keep the README as clean as possible, and this seems to be either a bug in some version of React Native CLI, or related to some very specific configuration.

I need some kind of example/demo of the exact problem that helps me to verify it before it can be added to the README.
