### ISSUE TITLE
kind-of Peer Dependency Upgrade

### ISSUE THREAD

**Issue by Anurag-Shrivastava** [kristerkari/react-native-svg-transformer#155]
### **Feature Request**

Hey,

Could you please upgrade the **"kind-of"** peer dependency to  6.0.3?

> ### **Why it is needed**

Our customers demand a security check and it fails over and over because of the old **"kind-of"** version used. You would save us a lot of work by doing that.

Thank you very much :)

**Comment by kristerkari** [comment]
@Anurag-Shrivastava sure, I will have a look at doing that.

**Comment by kristerkari** [comment]
This should be taken care of in the newest version.
