### ISSUE TITLE
 Unable to resolve module ./dashboard_active.svg from project\src\assets\images\icons\index.js without expo

### ISSUE THREAD

**Issue by Siva-Leo** [kristerkari/react-native-svg-transformer#156]
**metro.config.js**
```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

**Error**
![image](https://user-images.githubusercontent.com/68079920/141273654-3c5d5966-5a63-4d91-aacd-c3cc3f483531.png)

"react-native-svg": "^12.1.1",

"react-native-svg-transformer": "^0.14.3",

What I missed

**Comment by Siva-Leo** [comment]
its take a day of my life....Pls give me the solution

**Comment by kristerkari** [comment]
@Siva-Leo do you have an example project with the error that I can have a look at?

**Comment by Siva-Leo** [comment]
No, i have an example project...but i will create a new one and try...if its occur i'll give you the repo link

**Comment by Siva-Leo** [comment]
Problem in my SVG icon not in package
