### ISSUE TITLE
EXPO Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. 

### ISSUE THREAD

**Issue by adeyeanqar** [kristerkari/react-native-svg-transformer#159]
Hi, I use expo to build my app, I just recently upgrade from SDK 38 to SDK 41, I looked at the depreciations.. But I keep getting this error 

`Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Run `react-native link @react-native-community/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-community.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.`

I tried customizing `metro.config.js `(I created this file as I didn't have it before and tried to tweak it with response I say), But I noticed that my expo actually came with `babel.config.js` (I don't know if that's a problem). I have tried all the tweak I saw and its not working still. Please I need urgent help as I have a deadline.

**Comment by kristerkari** [comment]
@adeyeanqar Thanks,

This library is not related to the error, so I'm quite sure that the problems is elsewhere (related to @react-native-community/async-storage).
