### ISSUE TITLE
react-native-svg and react-native-svg-transformer error in iOS

### ISSUE THREAD

**Issue by noname181** [kristerkari/react-native-svg-transformer#160]
I have installed react-native-svg and react-native-svg-transformer successfully in Android, but in iOS I get this error. Has anyone got it before, and what is solution for it? Hope your help, thank you.
react-native: 0.66.3
react-native-svg-transformer: 0.14.3
react-native-svg: 12.1.1

metro.config.js

`const { getDefaultConfig } = require("metro-config");
module.exports = (async () => {
const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
`

![photo_2021-11-20_08-45-33](https://user-images.githubusercontent.com/41870695/142710051-d622006f-434e-44e8-8fdd-ba199769cbe3.jpg)

**Comment by kristerkari** [comment]
This has been discussed many times here before, no need to open a new issue about it.

The most common reason for this is either some misconfiguration, or then just that the Metro packager needs to be restarted.

Please have a look at the previous discussion: https://github.com/kristerkari/react-native-svg-transformer/search?q=type+is+invalid&type=issues
