### ISSUE TITLE
Update to latest SVGR

### ISSUE THREAD

**Issue by bfricka** [kristerkari/react-native-svg-transformer#162]
This package is a few versions behind SVGR. None of the links work any longer (e.g. options should point to [legacy docs](https://github.com/gregberge/svgr/blob/v4.3.3/website/src/pages/docs/options.mdx), but they link to 404). SVGR itself has had several updates that are relevant to this project. For one thing, there's a new `memo` option, which does exactly what you'd imagine. There's also a fix for react-native when `icon` is specified, since `1em` doesn't mean anything on react-native.  There's probably a ton more bug fixes and improvements, and it should be pretty easy to update.

This is a pretty old package and it hasn't been updated in a long time. There's an open PR that has been ignored for a few months, and none of the dependencies have been updated, even though there have been relevant issues opened. So I'm wondering what the status of this project actually is? This project is linked by `react-native-svg` and so is a pretty important solution for those who want import SVG-as-component functionality.

Is there an appetite for any further development?

Thank you.

**Comment by kristerkari** [comment]
The SVGR version should definitely be updated to a newer one.

**Comment by bfricka** [comment]
```js
const path = require('path')
const svgr = require('@svgr/core')
const metroTransformer = require('metro-react-native-babel-transformer')

/**
 * @see https://react-svgr.com/docs/options/
 */
const SVGR_CONFIG = {
  memo: true,
  native: true,
  replaceAttrValues: {
    '#000': '{props.fill}',
  },
}

/**
 * @param arg BabelTransformerArgs
 * @see https://github.com/facebook/metro/blob/main/packages/metro-babel-transformer/src/index.js
 */
module.exports.transform = async (arg) => {
  const ext = path.extname(arg.filename)

  if (ext !== '.svg' && ext !== '.svgx') return metroTransformer.transform(arg)

  const reactSvg = await svgr.transform(arg.src, SVGR_CONFIG)

  return metroTransformer.transform({ ...arg, src: reactSvg })
}
```
I did it quick and dirty, since I know which transformer to use for my version, and hardcoded the config. But doing the config search and all the stuff you're doing now is still easy w/ the latest SVGR. Only real difference is main transform is async, which is what is recommended, but I don't know if this affects old clients. Sync methods do exist. Everything works well.

**Comment by kristerkari** [comment]
Thanks for this @bfricka ! 

I'll try to find time during the Christmas holiday to get some updates out for this library. 

In the meantime Pull Requests are welcome (considering that there is some way of easily verify that the code changes work). :)

**Comment by kristerkari** [comment]
I updated a PR to update SVGR to the latest version: https://github.com/kristerkari/react-native-svg-transformer/pull/164

I also created a new branch to the example app to try out the changes and to cleanup the transformer code for the upcoming version: https://github.com/kristerkari/react-native-svg-example/tree/updated-svgr

**Comment by kristerkari** [comment]
Done and released.

Now I can start preparing the 1.0 version that will drop support for the really old React Native versions.

**Comment by bfricka** [comment]
Thanks @kristerkari
