### ISSUE TITLE
React Native 0.66.4 - Invariant Violation: View config getter callback for component ...

### ISSUE THREAD

**Issue by DwCleb** [kristerkari/react-native-svg-transformer#167]
I've using the RN 0.66.4 version, react-native-svg ^12.1.1 and react-native-svg-transformer ^1.0.0.

I've this error for all tries that I did.

```
Invariant Violation: View config getter callback for component `<svg width="41" height="40" viewBox="0 0 41 40" fill="none" >...` ...
must be a function (received `undefined`).

This error is located at:
    in <svg ...
```
![Simulator Screen Shot - iPhone 13 - 2022-01-05 at 21 23 43](https://user-images.githubusercontent.com/30187750/148291458-b6fa6276-5a84-48d2-aac7-2f4bc90c96dd.png)

my `metro.config.js`:

```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();

```

So, the react-native-svg-transformer is not available for this version?

**Comment by kristerkari** [comment]
The demo app is running 0.66.4, and it's working fine there. To me it looks from the error like the metro config would not be in effect.

@DwCleb did you try to restart the Metro packager and rebuild the app?

**Comment by DwCleb** [comment]
@kristerkari  I created a new project to test, and I also got this error.
Should I upload it to you take a look? :)

**Comment by kristerkari** [comment]
@DwCleb sure, I can have a look if you upload it somewhere :)

**Comment by DwCleb** [comment]
@kristerkari 
the repository with the demo project that I created:
https://github.com/DwCleb/SvgDemoApp-

**Comment by kito22** [comment]
Same problem here, with: 
RN 0.66.4
react-native-svg: 12.1.1
react-native-svg-transformer: 1.0.0.

When using elements from react-native-svg (Svg, Path) it works fine, but when using svg files, I have same issue "Invariant Violation: View config getter callback for component "

**Comment by kristerkari** [comment]
@DwCleb sorry for the late response, but I had a look at your project, and it's the `babel-plugin-inline-import` that is messing things up. I tried removing that Babel plugin from your project and it fixed the error.

**Comment by kristerkari** [comment]
I'm closing this since the problem got resolved. Let's re-open if something new comes up.

**Comment by DwCleb** [comment]
Worked like a charm!
Also I needed to remove it from babel.config

**Comment by tigerraj32** [comment]
It worked. I spend half a day to resolve this solution until i reach here.

**Comment by ngodangkhoa** [comment]
It worked, I spent couple day to fixing that. Thanks @kristerkari

**Comment by gegnew** [comment]
Same problem, but this does _not_ fix it for me; any idea what else could cause this?
