### ISSUE TITLE
Simple Svg works on iOS but not on Android

### ISSUE THREAD

**Issue by charity-detalytics** [kristerkari/react-native-svg-transformer#174]
# Bug

Simple Svg works on iOS but not on Android
<img width="570" alt="Screen Shot 2022-02-19 at 16 04 44" src="https://user-images.githubusercontent.com/63986409/154794383-a6fa762b-16d3-4a98-a189-c2404a8f4773.png">

## Steps To Reproduce

I have just created this new and simple repo for reproducing the issue:
https://github.com/charity-detalytics/SrgErr

```js
import React from 'react';
import type {Node} from 'react';
import {
  View,
} from 'react-native';
import X from './x.svg'

const App: () => Node = () => {
  return (
    <View>
      <X/>
    </View>
  );
};

export default App;
```

```svg
<svg width="100%" height="100%" viewBox="0 0 325 432">
  <mask id="id" x="143" y="278" width="182" height="69">
    <path d="M143.867 278.211H325V346.467H143.867V278.211Z" fill="white"/>
  </mask>
  <g mask="url(#id)">
    <path d="M167.267 323.524L487.933 264.391L818.133 323.524" stroke="red" stroke-width="13"/>
  </g>
</svg>

```

Describe what you expected to happen:
Please see the screen shot above!

**Comment by kristerkari** [comment]
I'm not sure why it looks different on Android and iOS, but it's the mask that is causing it not to render on Android.

**Comment by kristerkari** [comment]
Closing this as solved.
