### ISSUE TITLE
I get issue bug Invariant Violation: ViewPropTypes has been removed from React Native in react-native 0.69.1 and react 18.0.0

### ISSUE THREAD

**Issue by denialfarizi1** [kristerkari/react-native-svg-transformer#179]
i get issue in react-native 0.69.1 and react 18.0.0

Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'

![image](https://user-images.githubusercontent.com/40252418/177678941-7b5f31d5-375e-4730-a095-fc39a475acbb.png)

**Comment by kristerkari** [comment]
Not related to this library.
