### ISSUE TITLE
How change color of SVG Images

### ISSUE THREAD

**Issue by imbudhiraja** [kristerkari/react-native-svg-transformer#18]
How to change color of SVGs.

**Comment by kristerkari** [comment]
There is currently no support for that, but I'm open for ideas of how to implement that inside this library.

Related issue:
https://github.com/kristerkari/react-native-svg-transformer/issues/7

**Comment by kristerkari** [comment]
New version is out that supports replacing a color inside the SVG images. It's a bit lacking, but at least you can try it out to see if works for you project. More info can be found in the README.

https://github.com/kristerkari/react-native-svg-transformer/releases/tag/0.13.0

**Comment by imbudhiraja** [comment]
@kristerkari thanks a lot man, i'll check

**Comment by kristerkari** [comment]
There are now proper instructions in the README.
