### ISSUE TITLE
Update color of SVG?

### ISSUE THREAD

**Issue by spylefkaditis** [kristerkari/react-native-svg-transformer#22]
Is it possible to change the color of an imported svg image based on state updates? 
This doesn't work. The style is always primaryBlue even when the active value is true and the textSubdued should be applied.

`<Home color={active ? primaryBlue : textSubdued} />;`

**Comment by kristerkari** [comment]
Thanks @spylefkaditis !

This is a question that is asked quite often (https://github.com/kristerkari/react-native-svg-transformer/issues/7, https://github.com/kristerkari/react-native-svg-transformer/issues/18).

Currently when it comes to dynamically replacing the color, this library is limited to what SVGR  can provide:
https://github.com/smooth-code/svgr

I'm not currently sure if it is possible to do it, should try to read through the different options from SVGR to see if something could be used to do what you are asking for.

**Comment by spylefkaditis** [comment]
Thanks

**Comment by samridhgupta** [comment]
Any update on this ?

**Comment by kristerkari** [comment]
@samridhgupta Yes, check the readme https://github.com/kristerkari/react-native-svg-transformer#changing-svg-fill-color-in-js-code

**Comment by Sakarisson** [comment]
@kristerkari This is not an ideal solution. I want to be able to dynamically set the color of any SVG, regardless of what its base color was. Essentially what I'm looking for is functionality that is similar to `tintColor`.

**Comment by kristerkari** [comment]
@Sakarisson this library is using SVGR, so unfortunately we are limited to the replacement API that it offers. That means that currently you can have a fill color and replace it with another color at runtime.

If you have ideas of how to improve it, then I suggest that you open a new issue at SVGR's repository:
https://github.com/gregberge/svgr
