### ISSUE TITLE
[Question] Is it possible to overlay a text over the SVG element

### ISSUE THREAD

**Issue by nervouscat** [kristerkari/react-native-svg-transformer#24]
Hello,

I am currently trying to overlay a custom text over the SVG element:
```
import DiscountDisc from './Images/Icons/discount-disc.svg'
...
            <View>
            <DiscountDisc/>
            <Text>TEST</Text>
            </View>
```

is it possible to do so?

Thank you in advance!

**Comment by kristerkari** [comment]
Thanks @nervouscat!

I haven't tested, but you should be able to do that by giving the wrapping `<View>` element `position: "relative"` as a style and the other elements `position: "absolute"` and then positioning them.

**Comment by nervouscat** [comment]
Works Well! Thank you!

**Comment by iamabdulhaseeb** [comment]
@kristerkari Actually I want to overlay a scrollview over the svg but the scroll is not working :(
