### ISSUE TITLE
letter-spacing causes app to crash

### ISSUE THREAD

**Issue by nevace** [kristerkari/react-native-svg-transformer#26]
I've been trying to figure this issue out for a while now but it seems that adding a letter-spacing attribute to any element causes the app to crash.

This looks like an issue with react-native-svg itself, using a numeric value causes the crash as mentioned here:

https://github.com/react-native-community/react-native-svg/issues/568

Here's an example adapted from the issue above:

`			<Svg width={300} height={320} viewBox="0 0 32 32">
					<G fill="none" fillRule="evenodd">
						<Text
							fontFamily="Raleway-Bold, Raleway"
							fontSize={12}
							fontWeight="bold"
							letterSpacing={1}
							fill="#FF1E4F"
						>
							<TSpan x={10} y={20}>
								{`15`}
							</TSpan>
						</Text>
					</G>
				</Svg>`

The fix is to use a string as the value (letterSpacing={1} to letterSpacing="1") but since this transform automatically converts the value to a number, it will always crash. I'm not sure where the fix should be, in this library or in react-native-svg itself.

Any workarounds for it?

**Comment by kristerkari** [comment]
HI @nevace! The fix should be done in `react-native-svg`. I need to think if there is any easy workaround for the problem.

**Comment by msand** [comment]
This should've been fixed since: https://github.com/react-native-community/react-native-svg/commit/c343229441ade3e3422aba00de80b4ca50b8bbe1#diff-214abf2d48c6f1a6d396acd35c58e37c
I.e. since v9.5.0

**Comment by kristerkari** [comment]
@msand I just tested with the example code from this issue, and I could get it to crash on Android with both 9.5.1 and 9.6.2 versions. So `letterSpacing={1}` crashes, `letterSpacing="1"` doesn't.

**Comment by msand** [comment]
@kristerkari Can you try https://github.com/react-native-community/react-native-svg/commit/54f930a332360330879af4d4857b22642abfd11f

**Comment by kristerkari** [comment]
@msand I tried your fix, looks like it fixes the crash with the example code.

**Comment by kristerkari** [comment]
Closing this as the fix is included in `react-native-svg` 9.6.3 and newer versions.
