### ISSUE TITLE
Existing default Metro transforms interfere with `react-native-svg-transformer`

### ISSUE THREAD

**Issue by skhameneh** [kristerkari/react-native-svg-transformer#27]
Filing this issue equally for investigation and documentation for those whom may have been experience similar issues.  This information may be useful in troubleshooting various configurations.  
  
`experimentalImportSupport: false` and `inlineRequires: false` appear to break `react-native-svg-transformer`
```
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
```

I found an issue within `styled-components` produces when these are present with `babelTransformerPath: require.resolve("react-native-svg-transformer")`, see https://github.com/styled-components/styled-components/issues/2536

**Comment by skhameneh** [comment]
This may be an issue with the metro resolver.

**Comment by kristerkari** [comment]
Thanks @skhameneh for letting us know about this. 

I haven't noticed the problem yet, and the demo app is also updated to React Native 0.59.8: https://github.com/kristerkari/react-native-svg-example/blob/master/metro.config.js

Do you have some kind of example app or project to reproduce the issue?

**Comment by kristerkari** [comment]
Closing this as inactive. Let's re-open if something new comes up.
