### ISSUE TITLE
how to configure metro.config.js in 0.72.0

### ISSUE THREAD

**Issue by adsalihac** [kristerkari/react-native-svg-transformer#276]
This version they are changed metro config.

`
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const config = {};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
`

**Comment by ngondat97** [comment]
same issue

**Comment by jackfiallos** [comment]
I have added something like this, metro its running now but I haven't confirmed if the app will work after a RN 0.72.0 upgrade

```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts;
const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;
/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */

module.exports = mergeConfig(getDefaultConfig(__dirname), {
    transformer: {
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
        getTransformOptions: async () => ({
            transform: {
                experimentalImportSupport: false,
                inlineRequires: true,
            },
        }),
    },
    resolver: {
        assetExts: defaultAssetExts.filter(ext => ext !== 'svg'),
        sourceExts: [...defaultSourceExts, 'svg'],
    },
});

```

**Comment by adsalihac** [comment]
yes

**Comment by stefkampen** [comment]
works like a charm

**Comment by bayuengx1** [comment]
> I have added something like this, metro its running now but I haven't confirmed if the app will work after a RN 0.72.0 upgrade
> 
> ```js
> const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
> const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts;
> const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;
> /**
>  * Metro configuration
>  * https://facebook.github.io/metro/docs/configuration
>  *
>  * @type {import('metro-config').MetroConfig}
>  */
> 
> module.exports = mergeConfig(getDefaultConfig(__dirname), {
>     transformer: {
>         babelTransformerPath: require.resolve('react-native-svg-transformer'),
>         getTransformOptions: async () => ({
>             transform: {
>                 experimentalImportSupport: false,
>                 inlineRequires: true,
>             },
>         }),
>     },
>     resolver: {
>         assetExts: defaultAssetExts.filter(ext => ext !== 'svg'),
>         sourceExts: [...defaultSourceExts, 'svg'],
>     },
> });
> ```

Very helping bro, thank u so much. You save my life 😭

**Comment by abgaryanharutyun** [comment]
> I have added something like this, metro its running now but I haven't confirmed if the app will work after a RN 0.72.0 upgrade
> 
> ```js
> const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
> const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts;
> const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;
> /**
>  * Metro configuration
>  * https://facebook.github.io/metro/docs/configuration
>  *
>  * @type {import('metro-config').MetroConfig}
>  */
> 
> module.exports = mergeConfig(getDefaultConfig(__dirname), {
>     transformer: {
>         babelTransformerPath: require.resolve('react-native-svg-transformer'),
>         getTransformOptions: async () => ({
>             transform: {
>                 experimentalImportSupport: false,
>                 inlineRequires: true,
>             },
>         }),
>     },
>     resolver: {
>         assetExts: defaultAssetExts.filter(ext => ext !== 'svg'),
>         sourceExts: [...defaultSourceExts, 'svg'],
>     },
> });
> ```

Thank you so much @jackfiallos, this works 100000% 🚀

**Comment by RominHalltari** [comment]
This does not work for me, I'm getting the following error: 
![image](https://github.com/kristerkari/react-native-svg-transformer/assets/16745534/8fb647b2-5127-404e-9441-e6248d47a641)

**Comment by Adnan-Bacic** [comment]
> I have added something like this, metro its running now but I haven't confirmed if the app will work after a RN 0.72.0 upgrade
> 
> ```js
> const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
> const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts;
> const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;
> /**
>  * Metro configuration
>  * https://facebook.github.io/metro/docs/configuration
>  *
>  * @type {import('metro-config').MetroConfig}
>  */
> 
> module.exports = mergeConfig(getDefaultConfig(__dirname), {
>     transformer: {
>         babelTransformerPath: require.resolve('react-native-svg-transformer'),
>         getTransformOptions: async () => ({
>             transform: {
>                 experimentalImportSupport: false,
>                 inlineRequires: true,
>             },
>         }),
>     },
>     resolver: {
>         assetExts: defaultAssetExts.filter(ext => ext !== 'svg'),
>         sourceExts: [...defaultSourceExts, 'svg'],
>     },
> });
> ```

this works for me. i have made a small change. i think the empty `config` variable in the new template is meant as a way to have our own config for _readability_ if we want to avoid writing our own config inside the default config. then the new `mergeConfig` function merges them together.

so alternatively, i have it like this:

```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

const sourceExts = require('metro-config/src/defaults/defaults').sourceExts;
const assetExts = require('metro-config/src/defaults/defaults').assetExts;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => {
        return {
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        };
      },
    },
    resolver: {
      assetExts: assetExts.filter((ext) => { return ext !== 'svg'; }),
      sourceExts: [...sourceExts, 'svg'],
    },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

**Comment by kristerkari** [comment]
I'll update the docs as soon as I have tested that everything works with the suggested config / PR 🙂

**Comment by wjaykim** [comment]
From React Native 0.72.1 (with `"@react-native/metro-config": "^0.72.7"`), following works, too:
```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const path = require('path');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter(ext => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
  },
};

module.exports = mergeConfig(defaultConfig, config);
```

**Comment by trmylinh** [comment]
> This does not work for me, I'm getting the following error: ![image](https://user-images.githubusercontent.com/16745534/249032529-8fb647b2-5127-404e-9441-e6248d47a641.png)

Do you have a solution to fix that ?

**Comment by wjaykim** [comment]
@trmylinh Run `react-native start --reset-cache`

**Comment by trmylinh** [comment]
> @trmylinh Run `react-native start --reset-cache`

when I run `react-native --resert-cache`, it throw error 'Cannot read properties of undefined (reading 'filter').' in file metro.config.js @@

**Comment by wjaykim** [comment]
> when I run react-native --resert-cache, it throw error 'Cannot read properties of undefined (reading 'filter').' in file metro.config.js @@
You should install update `react-native` to `0.72.1` and `@react-native/metro-config` to `^0.72.7`

**Comment by trmylinh** [comment]
> > when I run react-native --resert-cache, it throw error 'Cannot read properties of undefined (reading 'filter').' in file metro.config.js @@
> 
> You should update `react-native` to `0.72.1` and `@react-native/metro-config` to `^0.72.7`

yeah, I have done update version like that, but it throw same error T.T

**Comment by trmylinh** [comment]
> @trmylinh Run `react-native start --reset-cache`

oh now it works, thank you so much

**Comment by twinart95** [comment]
> From React Native 0.72.1 (with `"@react-native/metro-config": "^0.72.7"`), following works, too:
> 
> ```js
> const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> const { assetExts, sourceExts } = defaultConfig.resolver;
> 
> /**
>  * Metro configuration
>  * https://facebook.github.io/metro/docs/configuration
>  *
>  * @type {import('metro-config').MetroConfig}
>  */
> const config = {
>   transformer: {
>     babelTransformerPath: require.resolve('react-native-svg-transformer'),
>   },
>   resolver: {
>     assetExts: assetExts.filter(ext => ext !== 'svg'),
>     sourceExts: [...sourceExts, 'svg'],
>   },
> };
> 
> module.exports = mergeConfig(defaultConfig, config);
> ```

this work for me, thaks

**Comment by adsalihac** [comment]
https://github.com/kristerkari/react-native-svg-transformer/blob/master/README.md

it is updated in README.md file.
