### ISSUE TITLE
Fails to find react-native-babel-transformer when used with React Native 0.73 because the package has been renamed

### ISSUE THREAD

**Issue by chriszs** [kristerkari/react-native-svg-transformer#317]
Per @gvarandas:

> The metro-react-native-babel-transformer package has been recently migrated to the [React Native monorepo](https://github.com/facebook/react-native/tree/main/packages/react-native-babel-transformer) and published/required under the @react-native/metro-babel-transformer alias.
>
> Starting with react-native@0.73.0, the new package is [loaded by default](https://github.com/facebook/react-native/blob/19945ad83b12c03d8b0931fd1a02bebabbc1a96b/packages/metro-config/package.json#L23), which makes the current implementation break when starting the metro bundler.

Specifically I get errors that it can't find the transformer package and can't load a transformer. See #312 for a potential solution.

**Comment by sirilisumba** [comment]
I resolved the problem by:
1. install @react-native/metro-babel-transformer
2. then edit metro.config.js:
....
transformer: {
    babelTransformerPath: require.resolve(
      '@react-native/metro-babel-transformer',
    ),
  },
....
3. restart

**Comment by kristerkari** [comment]
Thanks for reporting this, new version out:
https://github.com/kristerkari/react-native-svg-transformer/releases/tag/v1.2.0
