### ISSUE TITLE
Invariant Violation: View config not found for name <svg width

### ISSUE THREAD

**Issue by ithustle** [kristerkari/react-native-svg-transformer#33]
![61540727-18a60480-aa36-11e9-9b69-09b661061c9a](https://user-images.githubusercontent.com/5114680/61555920-63387880-aa58-11e9-8c2b-3d525bfccb35.png)

React native info output:

```
System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 1.40 GB / 11.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4
```

**Steps To Reproduce**
**Before**:
yarn add react-native-svg
yarn add react-native-svg-transformer -D

**After**
Enable hermes
yarn add babel-plugin-inline-import -D

myComponent.js

```
import React from "react";
import { Platform } from "react-native";

import IconHome from "./../imgs/icon/home.svg";
export const Home = props => ( <IconHome { ...props } width={22} height={22} /> );
...
```

screen.js

```
import { Search, Genero, MinhasMusicas, Home } from "./../components/Icon";
<Home key={1} />
```

**Comment by kristerkari** [comment]
Looking at the error, it looks like the transformer is not running for the SVG file. Would it be possible for you to upload your project somewhere where I could have a look at it?

**Comment by kristerkari** [comment]
I also have not tested the compatibility of `react-native-svg-transformer` with React Native 0.60.x yet.

**Comment by ithustle** [comment]
Hi @kristerkari . Thanks to be here and sorry for delay. Please FIA
[ithustle-toqueplay-d29670962b65.zip](https://github.com/kristerkari/react-native-svg-transformer/files/3416902/ithustle-toqueplay-d29670962b65.zip)

**Comment by kristerkari** [comment]
I haven't yet had time to look at the project that you uploaded.

I created a new React Native project and installed both react-native-svg and the transformer.

Everything was working fine, both on iOS and Android (with Hermes disabled and enabled), so this looks like something related to the project/configuration.

**Comment by dilipchandima** [comment]
<img width="518" alt="Screen Shot 2019-08-01 at 10 23 40 AM" src="https://user-images.githubusercontent.com/9445375/62266589-7bd86380-b446-11e9-9558-5e47c909f60c.png">

I'm facing this issue I'm working on React-native 0.60.4

**Comment by kristerkari** [comment]
@dilipchandima From that error it's difficult to even say if the error is related to the svg tranformer. Usually the errors with the svg transformer are related to it not being configured correctly.

**Comment by ithustle** [comment]
Another thing... svg images with gradient doesn’t work
>I haven't yet had time to look at the project that you uploaded. ...

@kristerkari 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dilipchandima** [comment]
@kristerkari I just created a fresh app and added svg transformer it has the same issue [https://github.com/kristerkari/react-native-svg-transformer/issues/url](url)

**Comment by dilipchandima** [comment]
@kristerkari I just tested for react-native 0.59.2 it is working fine but I didnt do anything other than for 0.60.4 project

**Comment by kristerkari** [comment]
@dilipchandima I also tested creating a new React Native project + adding the transformer last week and everything was working just fine. Can you please upload the project that you have so that I can have a look at it?

**Comment by dilipchandima** [comment]
@kristerkari just fix the issue but for that i need to remove the following code from the metro config I dont have mush idea about that
```

const defaultModule = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by kristerkari** [comment]
> Another thing... svg images with gradient doesn’t work

`react-native-svg` supports gradients, but some images might have some other unsupported things that cause the image to not render correctly.

Did you get the react-native-svg-transformer setup to work @ithustle ?

**Comment by ithustle** [comment]
> > Another thing... svg images with gradient doesn’t work
> 
> `react-native-svg` supports gradients, but some images might have some other unsupported things that cause the image to not render correctly.
> 
> Did you get the react-native-svg-transformer setup to work @ithustle ?

Yep, but in some images not all.

**Comment by kristerkari** [comment]
Okay, this issue seems to be going quite off-topic. Please open a new issue with the specific problem if there still is one.
