### ISSUE TITLE
Unexpected import of expo metro config

### ISSUE THREAD

**Issue by Titozzz** [kristerkari/react-native-svg-transformer#333]
We use expo libraries without expo-cli.
Theses lines of code will use the wrong transformer based only on the fact that expo metro config exists in node_modules.

```tsx
/**
 * `metro-react-native-babel-transformer` has recently been migrated to the React Native
 * repository and published under the `@react-native/metro-babel-transformer` name.
 * The new package is default on `react-native` >= 0.73.0, so we need to conditionally load it.
 *
 * Additionally, Expo v50.0.0 has begun using @expo/metro-config/babel-transformer as its upstream transformer.
 * To avoid breaking projects, we should prioritze that package if it is available.
 */
const upstreamTransformer = (() => {
  try {
    return require("@expo/metro-config/babel-transformer");
  } catch (error) {
    try {
      return require("@react-native/metro-babel-transformer");
    } catch (error) {
      return require("metro-react-native-babel-transformer");
    }
  }
})();
```
You shouldn't assume the transformer based on dependencies, so I'd suggest an extra param / option!
What do you think 😃  ?

**Comment by kristerkari** [comment]
Previously there was always only one Babel transformer per project, but now that Expo introduced its own transformer the code is just expecting there to be either Expo or React Native transformer, not both.

Adding an option to override the transformer path would be one way to handle this problem.

**Comment by kristerkari** [comment]
I've been thinking that the easiest fix for now might be just to add more checks to try to verify that the app is a real Expo app, and not just a project that happens to have some expo dependencies installed.

**Comment by ravindran-a** [comment]
+1

**Comment by kristerkari** [comment]
Regarding React Native projects that happen to use some Expo dependencies, I have opened a PR #366 to add support for defining the transformer based on the project: 

```diff
-require.resolve("react-native-svg-transformer")
+require.resolve("react-native-svg-transformer/react-native")
```

This is only additional config, and won't need migration for existing projects.

Please let me know if you think that this is good appoarch to work around the problem.

**Comment by Titozzz** [comment]
@kristerkari this PR is 💯 . Thanks for the idea

**Comment by kristerkari** [comment]
@Titozzz thanks for reporting the problem, and please let me know if you run into any problems with the newest version. 👍
