### ISSUE TITLE
Unable to resolve SVG file

### ISSUE THREAD

**Issue by chin8628** [kristerkari/react-native-svg-transformer#35]
Hi, I've been trying to import SVG file to use in my react-navigation file as an icon. I installed the library as you write in the readme file. But, I got an error.

`Unable to resolve "./assets/icons/bottom_tab/profile_active.svg" from "MainNavigation.js"
Failed building JavaScript bundle.`

I've been checked my file, and I'm really sure that the svg file is in right directory.

My environment: 
- expo: 33
- react-native-svg: 9.4.0
- react-native-svg-transformer: 0.13.0

I got this error on both android and ios.

**Comment by nelsera** [comment]
I have the same problem :(

**Comment by aktitarov** [comment]
+ 1 have the same issue

**Comment by pachoclo** [comment]
+1

**Comment by arthuryeti** [comment]
+1

**Comment by jdaoliveira** [comment]
+1

**Comment by zanechua** [comment]
For those using expo, most likely it's due to the breaking change of the new expo-cli v3.

Please see:
https://github.com/expo/expo-cli/issues/875

**Comment by chin8628** [comment]
Thank you! @zanechua 
Since we already found the solution. I will close this issue.

**Comment by AnayoOleru** [comment]
How about those not using expo?
