### ISSUE TITLE
SVG with react native Animated

### ISSUE THREAD

**Issue by OriginLive** [kristerkari/react-native-svg-transformer#36]
Hi, any idea how to use Animated (react native) with svgs? Setting it's height and width to an animated value does not seem to work.

**Comment by kristerkari** [comment]
Hi @OriginLive! If you need to animate SVGs, then I would suggest to use plain `react-native-svg` with its React components to do that.

**Comment by OriginLive** [comment]
so i assume 

`import Logo from '../../assets/img/logo_main_big.svg';

...

          <Logo width={572 / 3} height={615 / 3} />

`

Is actually react-native-svg, even though i'm loading it through transformer?

**Comment by kristerkari** [comment]
> Is actually react-native-svg, even though i'm loading it through transformer?

Yes, that's correct.
