### ISSUE TITLE
Does not working with react native 0.60.4 -  Invariant Violation

### ISSUE THREAD

**Issue by dilipchandima** [kristerkari/react-native-svg-transformer#38]
Facing a issue with react-native-svg-transformer with react native latest version 0.60.4

- react-native-svg is working fine with react-native 0.60.4

This is public git repo I have created for example react-native-svg-transformer with react-native 0.60.4 - [https://github.com/dilipchandima/reactNative6SVG](url)

following are my configurations for react native

package.json
```
{
  "name": "svg",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-svg": "^9.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-native-svg-transformer": "^0.13.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

metro.config

```
const { getDefaultConfig, mergeConfig } = require("metro-config");

const svgModule = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();

const defaultModule = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};

module.exports = mergeConfig(svgModule, defaultModule);
```

<img width="518" alt="Screen Shot 2019-08-01 at 11 50 37 AM" src="https://user-images.githubusercontent.com/9445375/62270409-a0870800-b453-11e9-8510-95b94e2fbf3c.png">

**Comment by dilipchandima** [comment]
after I change the metro config as following it works 
```

const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();

```

**Comment by baleo-it** [comment]
Adding `babelTransformerPath: require.resolve("react-native-svg-transformer")`into `metro.config.js` breaks our metro config and debugger is not showing any information anymore.

We are using :
- "@babel/plugin-proposal-decorators": "^7.6.0"
- "react-native-svg-transformer": "^0.13.0"
- "react-native-svg": "^9.9.3"
- "react-native-vector-icons": "^6.6.0"
- "react-native-elements": "^1.2.0"

Experimented on OSX with a fresh new RN 0.60.5 project, editing dependencies in package.json, metro.config.js with documentation sample code.

This code makes debugger working:
```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();

  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      })
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

This code makes debugger not working:
```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();

  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'), <--- this line
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

**Comment by Simek** [comment]
Refs:  #14, #29

**Comment by kristerkari** [comment]
I'll update the demo app to 0.60, and let's see if I get the same issue.

**Comment by Simek** [comment]
I have fixed this issue by rewriting my config to:
```
const cfg = async () => await getDefaultConfig();

module.exports = mergeConfig(cfg, {
	transformer: {
		getTransformOptions: async () => ({
			transform: {
				experimentalImportSupport: false,
				inlineRequires: false
			}
		}),
		babelTransformerPath: require.resolve("react-native-svg-transformer")
	},
	resolver: {
		assetExts: assetExts.filter(ext => ext !== "svg"),
		sourceExts: [...sourceExts, "svg"],
		blacklistRE: blacklist([/ios\/Pods\/.*/])
	}
});
```

In my case there was a problem with async/await construction from example .

**Comment by baleo-it** [comment]
@Simek how do you get `assetExts` and `sourceExts` defined?

**Comment by Simek** [comment]
@baleo-it Thank you for pointing this out, my bad, I have missed this line while copying my config:
`const { assetExts, sourceExts } = require('metro-config/src/defaults/defaults');`

**Comment by OzzyTheGiant** [comment]
If anyone is using Expo with their project, **restart** the development server. Apparently you need to do this to load config file correctly. It's such a simple thing that anyone could miss but that helped me out after getting the same exact error. Can confirm this is working with default metro.config.js, typescript declaration file, .svgrrc file, and app.json settings.

**Comment by bernardodesousa** [comment]
Using a config similar to @Simek's and restarting the Metro server solved the problem to me. However, Typescript isn't happy:

`Cannot find module './0.svg' or its corresponding type declarations. ts(2307)`

I don't if it even makes sense, but is there a way to "type" SVG files?

**Comment by TheOmran** [comment]
@bernardodesousa create a directory at `./src/@types/assets` and add an `index.d.ts` file there with the following content.

```declare module "*.svg" {
  import { SvgProps } from "react-native-svg";
  const content: React.FC<SvgProps>;
  export default content;
}
```
