### ISSUE TITLE
 app cannot build with react-native-reanimated@3.16.1

### ISSUE THREAD

**Issue by camxus** [kristerkari/react-native-svg-transformer#391]
` ERROR  ReanimatedError: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.16.1 vs 3.10.1).
    See `https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#mismatch-between-javascript-part-and-native-part-of-reanimated` for more details., js engine: hermes [Component Stack]`

**Comment by kristerkari** [comment]
@camxus This plugin has nothing to with Reanimated, so your error is coming from something else. Hopefully you'll manage to fix it 👍
