### ISSUE TITLE
Changing SVG fill color in JS Code -- need processColor() for IOS

### ISSUE THREAD

**Issue by mdalpozzo** [kristerkari/react-native-svg-transformer#40]
Followed the steps under [https://github.com/kristerkari/react-native-svg-transformer#changing-svg-fill-color-in-js-code](url).

Called my svg element like so:
`<Account width={100} height={100} color={'red'} />`

Works fine in Android.  SVG icon is red yay.  Problem is in IOS I get this error:
`JSON value of 'red' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?

Changed to:
```
import {processColor} from 'react-native';
...
<Account width={100} height={100} color={processColor('red')} />
```

and then it worked in IOS, but causes issues in Android.
Only way I can see to do it now is:
```
import {processColor, Platform} from 'react-native';
...
<Account width={100} height={100} color={Platform.OS === 'ios' ? processColor('red') : 'red'} />
```

Anyone experienced this or have a better idea of how to solve this?  End of day tired and haven't looked through this package source code to investigate further.

**Comment by kristerkari** [comment]
Thanks @mdalpozzo ! This looks like it might be related to the `react-native-svg` or SVGR libraries.

Which version of SVGR and react-native-svg are you using? Does it work on iOS if you use a hex color instead of a named color?

**Comment by mdalpozzo** [comment]
"react-native-svg-transformer": "^0.13.0",
"react-native-svg": "^9.6.2",
"react-native": "0.60.4"

hex colors have the same behavior

**Comment by kristerkari** [comment]
Hey @mdalpozzo, I just tried in the demo project and I'm getting the same error as you are on iOS.

**Comment by kristerkari** [comment]
@mdalpozzo I could get it to work by calling the prop both in the config and the component `fill` instead of `color`. Can you try if that fixes it for you too?

**Comment by mdalpozzo** [comment]
thanks! thats the trick

**Comment by bruscantini** [comment]
@kristerkari Which config are you referring to? I'm trying to follow your solution. Do you mean in the .svg file itself? Then I could only choose one color per file?
