### ISSUE TITLE
Unable to resolve "react-native-svg" from "assets/icon/cancel-exit.svg"

### ISSUE THREAD

**Issue by pavlov-sergey-alexandr** [kristerkari/react-native-svg-transformer#48]
After migrate from Expo SDK32 to Expo SDK35 I get an error - 'Unable to resolve "react-native-svg" from "assets / icon / cancel-exit.svg"'. I installed the library as you write in the readme file.

My package.json is the following:
"dependencies": {
    "expo": "^35.0.0",
    "expo-asset": "~7.0.0",
    "expo-camera": "~7.0.0",
    "expo-constants": "~7.0.0",
    "expo-file-system": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-localization": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "key-mirror": "^1.0.1",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-flash-message": "^0.1.13",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-image-gallery": "^2.1.5",
    "react-native-indicator": "^1.0.0",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-navigation": "^4.0.7",
    "react-navigation-stack": "^1.9.0",
    "react-redux": "6.0.0",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "remote-redux-devtools": "0.5.16",
    "scheduler": "^0.15.0"
  },
  "devDependencies": {
    "@babel/plugin-transform-react-jsx-source": "^7.2.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-preset-expo": "^7.0.0",
    "react-native-svg-transformer": "^0.13.0"
  },

My app.json is the following:
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": ["js", "jsx", "ts", "tsx", "svg"]
    },
    "assetBundlePatterns": ["**/*"]

My metro.config.js:
 const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg']
    }
  };
})();

Please help, Tks!

**Comment by kristerkari** [comment]
You need to install the `react-native-svg` library too: https://github.com/react-native-community/react-native-svg

**Comment by kristerkari** [comment]
Oh, it seems that the library should ship with Expo, in that case I have no idea.

**Comment by pavlov-sergey-alexandr** [comment]
Thank you! Your solution works.

yarn add react-native-svg

This is genius solution. Error in expo documentation for SDK 35
