### ISSUE TITLE
Can't import svgs

### ISSUE THREAD

**Issue by GammelBro** [kristerkari/react-native-svg-transformer#6]
If I want to import my svg like `import Star from '../../assets/svgs/pinnedStar.svg';`
I get this error 

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: number.`

my rn-cli.config.js:
```
const { getDefaultConfig, mergeConfig } = require('metro-config');

module.exports = mergeConfig(
  async () => {
    const {
      resolver: { sourceExts, assetExts },
    } = await getDefaultConfig();
    console.log(sourceExts);

    return {
      transformer: {
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
      },
      resolver: {
        assetExts: assetExts.filter(ext => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg'],
      },
    };
  },
  {
    transformer: {
      babelTransformerPath: require.resolve(
        'react-native-typescript-transformer'
      ),
    },
  }
);
```

**Comment by kristerkari** [comment]
This has been inactive for quite a while, so I guess that the problem got solved.

**Comment by dayaki** [comment]
Am having same error using RN 0.58, I created the `metro.config.js` and add the content `const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();`

but am still getting the same error. Any help, please.

**Comment by kristerkari** [comment]
@dayaki Can you post your config here or somewhere where I can see it?

**Comment by kristerkari** [comment]
@dayaki also, have a look at the example app to see how the transformer is used there: https://github.com/kristerkari/react-native-svg-example

**Comment by dayaki** [comment]
@kristerkari this is the content of my metro.config.js file
`
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})()'
Note: am using `react-native-cli` and not expo, also React native v0.58. Looking at your example app, I dont have a `webpack.config.js`, does it matter? Should I create it?

**Comment by kristerkari** [comment]
@dayaki The`webpack.config.js` is only used to render the same code for Web.

Your config looks fine, so the issue is probably somewhere else.

**Comment by dayaki** [comment]
I started a new RN app and it worked out of the box. Thanks

**Comment by kristerkari** [comment]
Good that you got your problem solved 👍  Let me know if you run into any other issues.

**Comment by danbockapps** [comment]
@kristerkari I got the same error as in the OP when trying to add this to my Expo/TypeScript project. This is with Expo 32 (which is RN 0.57). I had added the metro.config.js in the project root alongside app.json (didn't have that file before) and added the packagerOpts section to app.json.

TypeScript also complains about the import statement. "Cannot find module '../assets/search.svg'."

**Comment by kristerkari** [comment]
@danbockapps I have a working example that has Expo 32 and `react-native-svg-transformer` installed. 

You can compare your own project to it:
https://github.com/kristerkari/react-native-svg-expo-example

**Comment by kristerkari** [comment]
@danbockapps and for typescript you might need to do `declare module "*.svg";`, I'm not sure, but you can try that.

**Comment by danbockapps** [comment]
I forked react-native-svg-expo-example and successfully added TypeScript using the [Expo instructions](https://docs.expo.io/versions/latest/guides/typescript/). I submitted pull request #21 on this project to add the declaration to the readme.

I'm still getting the error on my existing project, so I still need to figure out what the difference is there. Thanks for your help!

**Comment by danbockapps** [comment]
I figured out my error - it was because I had react-native-typescript-transformer installed even though I don't need it (because I'm using Expo). I had installed TypeScript using [TypeScript's instructions for adding TypeScript to a React Native project](https://github.com/microsoft/TypeScript-React-Native-Starter) when I should have used [Expo's instructions for adding TypeScript to an Expo project](https://docs.expo.io/versions/latest/guides/typescript/). I uninstalled react-native-typescript-transformer and I can see SVGs in my app now.

**Comment by kristerkari** [comment]
@danbockapps Good that you got your problem solved. `react-native-typescript-transformer` is not needed in Expo or React Native if the version is at least 0.57.x, but it was used for older versions to get Typescript to work.

**Comment by idudinov** [comment]
Just wanted to comment on Typescript + Expo. Expo still (SDK v33) uses Babel for transforming for TS, so some TS features remain unavailable. Details: https://github.com/ds300/react-native-typescript-transformer#babel-caveats

So using [multiple transformers](https://github.com/kristerkari/react-native-css-modules/blob/master/docs/multiple-transformers.md#step-3-configure-transformer) was working solution for me in the case of using Typescript Namespaces.

**Comment by kristerkari** [comment]
> Just wanted to comment on Typescript + Expo. Expo still (SDK v33) uses Babel for transforming for TS, so some TS features remain unavailable. Details: https://github.com/ds300/react-native-typescript-transformer#babel-caveats
> 
> So using [multiple transformers](https://github.com/kristerkari/react-native-css-modules/blob/master/docs/multiple-transformers.md#step-3-configure-transformer) was working solution for me in the case of using Typescript features like Namespaces.

Sure, for most users it's enough to use Babel's TS, but yeah there are some special features left out that some users might need.

**Comment by Sankalp-Saxena** [comment]
@kristerkari svg image is opening on devices but not on web getting following error,

DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/events-qengage.89418f90.svg') is not a valid name.

**Comment by cj** [comment]
I am getting the exact same error for web (ios and android work just fine)

```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/cr-image.e8dcca4c.svg') is not a valid name.
```

**Comment by kristerkari** [comment]
@Sankalp-Saxena @cj are you guys using Expo? I think that that is a different error.

**Comment by Sankalp-Saxena** [comment]
@kristerkari Yes i am using expo and on web developer mode it cannot find that svg.

**Comment by shubhamdeol** [comment]
any solution to this?
I am having same error using expo web

**Comment by moh3n9595** [comment]
Same issue in bare react-native project 0.63.2

**Comment by christophby** [comment]
Same issue. My declarations.d.ts is in the root.
Package 0.14.3 (currently latest)
Typescript 4.0.3
RN  0.63.3
![image](https://user-images.githubusercontent.com/12933672/95459321-c4a57980-0973-11eb-856a-328982fa3777.png)

**Comment by christophby** [comment]
My issue was fixed by **NOT** putting the declarations.d.ts file in the root
Here's my PR by mentioning this in the README  https://github.com/kristerkari/react-native-svg-transformer/pull/109

**Comment by TomPeak** [comment]
Working with Expo … same error. PLZ help.

**Comment by RemyMachado** [comment]
> My issue was fixed by **NOT** putting the declarations.d.ts file in the root
> Here's my PR by mentioning this in the README #109

Where should we put it?
