### ISSUE TITLE
Stroke color is not transformed correctly

### ISSUE THREAD

**Issue by taneba** [kristerkari/react-native-svg-transformer#60]
I tried to change color by passing color code to stroke prop like this: 

```
<Logo stroke={colorCodeVariable} />
```

It works as I expected in local development (I'm using expo), but in production stroke color is not changed whatsoever.

The svg file is like:

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="..." stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M22.7896 1.21045L10.4673 13.5352" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by kristerkari** [comment]
I'm not sure if that is even supported. The SVG images are transformed by SVGR to a format like this, so the `stroke` will be applied to the `<svg>` element.

```jsx
import React from 'react'

const SvgComponent = props => (
  <svg width="1em" height="1em" viewBox="0 0 48 1" {...props}>
    <path d="M0 0h48v1H0z" fill="currentColor" fillRule="evenodd" />
  </svg>
)

export default SvgComponent
```

**Comment by harshitaahuja** [comment]
@kristerkari @taneba I am also facing issue with this... changing fill color to #000 and setting fill attribute worked, but stroke is not working in similar way.
Please suggest what change can be made in svg
```
<svg xmlns="http://www.w3.org/2000/svg" width="25.232" height="20.828" viewBox="0 0 25.232 20.828">
    <defs>
        <style>
            .cls-1{fill:#000}.cls-2{fill:none;stroke:#000;stroke-linecap:round;stroke-width:2px}
        </style>
    </defs>
    <g id="Group_282" data-name="Group 282" transform="translate(-341.982 -580.086)">
        <g id="eye" transform="translate(214.982 441.634)">
            <path id="Path_3203" d="M12.616 98.725c-4.821 0-9.193 2.638-12.419 6.922a1 1 0 0 0 0 1.192c3.226 4.289 7.6 6.927 12.419 6.927s9.193-2.638 12.419-6.922a1 1 0 0 0 0-1.192c-3.226-4.289-7.598-6.927-12.419-6.927zm.346 12.816a5.307 5.307 0 1 1 4.95-4.95 5.31 5.31 0 0 1-4.95 4.95zm-.16-2.447a2.858 2.858 0 1 1 2.669-2.669 2.853 2.853 0 0 1-2.671 2.67z" class="cls-1" data-name="Path 3203" transform="translate(127 43)"/>
        </g>
        <path id="Line_6" d="M0 18L18 0" class="cls-2" data-name="Line 6" transform="translate(345.5 581.5)"/>
    </g>
</svg>
```

**Comment by kristerkari** [comment]
@harshitaahuja The stroke does not work the same way because the library (SVGR) that is used to transform the SVG images to a format that React Native supports has a very simple API for replacing attribute values. 

So if you use the `replaceAttrValues` in a config, it's just going to look for a color and replace it with another one.

If you give the component (image) a value like `stroke="#000"`, it will just pass that value to the `<svg />` element, which does not work.

**Comment by taneba** [comment]
@kristerkari @harshitaahuja 
In my case, it eventually worked somehow.
What I did here is to add .svgrrc like below

```
{
  "replaceAttrValues": {
    "#000": "{props.stroke}"
  }
}
```

In fact I had done this before I open this issue, but I think I missed something at that time.
As @kristerkari said, svg-transformer simply does pass it's props to svg element, and replaceAttrValues makes change from #000 to the color you passed as stroke prop on svg element.

**Comment by kristerkari** [comment]
This seems resolved, so closing.

**Comment by codeYard17** [comment]
@taneba is it really worked! as it did not work for me

**Comment by alexzobi** [comment]
@codeYard17 i have found that i have to restart my metro bundler and clear my cache by first killing my bundler instance then running `npx react-native start --reset-cache`

**Comment by netojose** [comment]
After try for a long time, I fixed clearing the expo cache starting the server with a specific flag:

`npx expo start --clear`

**Comment by martinezguillaume** [comment]
> @kristerkari @harshitaahuja In my case, it eventually worked somehow. What I did here is to add .svgrrc like below
> 
> ```
> {
>   "replaceAttrValues": {
>     "#000": "{props.stroke}"
>   }
> }
> ```
> 
> In fact I had done this before I opened this issue, but I think I missed something at that time. As @kristerkari said, svg-transformer simply does pass it's props to svg element, and replaceAttrValues makes change from #000 to the color you passed as stroke prop on svg element.

thank you ! very simple solution for a complex problem, nice 👌
