### ISSUE TITLE
Add documentation to create svgMock with ts extension

### ISSUE THREAD

**Issue by davidsonsns** [kristerkari/react-native-svg-transformer#61]
I believe that could be helpful to add documentation to create a `svgMock` file for typescript project. Maybe people want to add just `.ts` files in your folder structure.

To fix on my current project I did it:

```ts
const exported = 'SvgMock';
export const ReactComponent = exported;
export default exported;
```

If sounds good I can contribute to the project with this adding it on the documentation.

**Comment by kristerkari** [comment]
Sorry, I don't quite understand what you mean here. There is already documentation for adding a mock file to your project, is that not enough?

**Comment by kristerkari** [comment]
I'm closing this as inactive, let's re-open if something new comes up.

**Comment by JSanchezIO** [comment]
I ran into an error that I believe the original author was trying to convey. My project uses Typescript and Jest. Using the documentation provided on mocking this library doesn't work. However, using the author's suggestion the mock works.

**Comment by jeandiego** [comment]
Just to contribute to anyone trying to use the .js setup in a TypeScript project, follow @davidsonsns's suggestion and everything will work.

> I believe that could be helpful to add documentation to create a `svgMock` file for typescript project. Maybe people want to add just `.ts` files in your folder structure.
> 
> To fix on my current project I did it:
> 
> ```ts
> const exported = 'SvgMock';
> export const ReactComponent = exported;
> export default exported;
> ```
> 
> If sounds good I can contribute to the project with this adding it on the documentation.

**Comment by davidsonsns** [comment]
tbh i don't remember exactly the issue (pls lemme know if im overcomplicating things @jeandiego - btw mentioning you because you were the most recent person to comment).

**_but the issue is_**: if a project only include `ts` files (or at least try to do so), most of the time maintainers will try to create `__mocks__/svgMock.ts` (with `.ts`) rather than `__mocks__/svgMock.js` (with `.js`).

so we could introduce something like below to the README:
```ts
// __mocks__/svgMock.js
module.exports = "SvgMock";
module.exports.ReactComponent = "SvgMock";

// TS version
// __mocks__/svgMock.ts
const exported = 'SvgMock';
export const ReactComponent = exported;
export default exported;
```

off-topic: damn! my english was really bad back in 2019 (It's still not perfect, but it's gotten a little better). my bad @kristerkari
