### ISSUE TITLE
Using the library with React navigation 5 makes Android to crash 

### ISSUE THREAD

**Issue by alexhoo** [kristerkari/react-native-svg-transformer#73]
Using this library in addition with the recently released react-navigation 5 makes expo android's apps to crash without any information.

**Comment by glennreyes** [comment]
Related issue at react-navigation repo to this: https://github.com/react-navigation/react-navigation/issues/6919

**Comment by rodriguezmanu** [comment]
also react-navigation 4 version

**Comment by glennreyes** [comment]
I just posted a working workaround here: https://github.com/react-navigation/react-navigation/issues/6919#issuecomment-592093015

**Comment by kristerkari** [comment]
Nice, thanks for the workaround!
