### ISSUE TITLE
Merge the contents from your project's metro.config.js file with this config (create the file if it does not exist already).

### ISSUE THREAD

**Issue by eladgel** [kristerkari/react-native-svg-transformer#77]
I've used a boilerplate react native project with the attached below metro.config.js file:

How should I edit it to support this library?
![image](https://user-images.githubusercontent.com/412137/76678483-1bff8900-65e1-11ea-8c2b-f00dcb8c8276.png)

This is what I did:
![image](https://user-images.githubusercontent.com/412137/76678601-15254600-65e2-11ea-823f-27e7da23c6c0.png)

**Comment by fireridlle** [comment]
Similar issue for me, getting error
```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

```

**Comment by kristerkari** [comment]
Thanks @eladgel and @fireridlle. If you are having problems with getting the configuration to work, could you please upload your project somewhere where I can have a look at it?

It's very difficult for me to help without seeing the project setup. What you can also do is try to create a new React Native project and just try the transformer out there to see how the setup is done before trying to set it up for your projects.

**Comment by fireridlle** [comment]
@kristerkari thank you for response. i have found some project at github and simply copied config from there. here is what i have 

`const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
`

**Comment by kristerkari** [comment]
That is the same config as in the example project: https://github.com/kristerkari/react-native-svg-example/blob/master/metro.config.js

Are you able to run the example project?

**Comment by eladgel** [comment]
@kristerkari sorry for the late response. I think it's all working

**Comment by pke** [comment]
> @kristerkari thank you for response. i have found some project at github and simply copied config from there. here is what i have
> 
> ```
> const {getDefaultConfig} = require('metro-config');
> 
> module.exports = (async () => {
>   const {
>     resolver: {sourceExts, assetExts},
>   } = await getDefaultConfig();
>   return {
>     transformer: {
>       getTransformOptions: async () => ({
>         transform: {
>           experimentalImportSupport: false,
>           inlineRequires: false,
>         },
>       }),
>       babelTransformerPath: require.resolve('react-native-svg-transformer'),
>     },
>     resolver: {
>       assetExts: assetExts.filter(ext => ext !== 'svg'),
>       sourceExts: [...sourceExts, 'svg'],
>     },
>   };
> })();
> ```

This should be in the README. This "merging" is more complex than the README suggests.

**Comment by kristerkari** [comment]
> This should be in the README. This "merging" is more complex than the README suggests.

The problem is that people might have changed the default configuration and added their own settings to `metro.config.js`, so that's why the readme suggests that you "merge" the existing file with the changes.

**Comment by pke** [comment]
I understand. People will find this issue here when they run into problems ;)

btw, do you know why SVGs is not supported by the core react-native code?
