### ISSUE TITLE
Where to find .svgrrc

### ISSUE THREAD

**Issue by schmru** [kristerkari/react-native-svg-transformer#79]
Hi,

I am working on changing the color of svg files on my application. I followed the instructions to install your lib and got it working but now, when I want to change the color, I cant find .svgrrc file to add replaceAttrValues line. 

I installed:
"react-native-svg": "9.13.3",
"react-native-svg-transformer": "^0.14.3"
Am I missing something or can someone please tell me where to find it.

**Comment by kristerkari** [comment]
Hi @schmru,

the `.svgrrc` is an optional configuration file that you can add to your project's root.

Here's the documentation from SVGR's website:
https://react-svgr.com/docs/configuration-files/

**Comment by schmru** [comment]
Thank you for the info
