### ISSUE TITLE
react-native with expo. SVG Image is not shown with static file

### ISSUE THREAD

**Issue by XOneto9** [kristerkari/react-native-svg-transformer#80]
Expo: 36.0.0(with eject)
react: 16.9.0
react-native: sdk-36(with expo)
react-native-svg-transformer: ^0.14.3
react-native-svg: 12.0.3

Hi, I'm using react-native with expo.
And I was followed This(react-natvie-svg-transformer) document guide line.

But the result is nothing.
I can not see anything.. also doesn't have error. just does not show.

```
import React from "react";
import styled from "styled-components";
import Layout from "../../constants/Layout";
import Header_background from "../../assets/PNG/header_background.png";
import { useHeaderHeight } from "@react-navigation/stack";
import Chat from "../../assets/SVG/chat.svg";

const Container = styled.View`
  background-color: white;
`;

const HeaderContainer = styled.Image`
  width: ${Layout.width}px;
  height: ${props => Layout.height / 3}px;
  top: 0px;
  /* position: absolute; */
`;

const LensPresenter = () => {
  const headerHeight = useHeaderHeight();
  console.log(headerHeight);
  const xml = `
 
  `;
  return (
    <Container>
      <HeaderContainer source={Header_background} height={headerHeight} />
      <Chat width="100%" height="100%" /> // here is SVG as Test
    </Container>
  );
};

LensPresenter.prototype = {};

export default LensPresenter;
```

![스크린샷 2020-03-18 오전 1 52 20](https://user-images.githubusercontent.com/18350072/76880514-1e9cff80-68bb-11ea-94c4-d282be0926e7.png)

*** origin svg file image code ***
```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 300 300" enable-background="new 0 0 300 300" xml:space="preserve">
<g>
	<rect x="93.3" y="146.7" width="113.3" height="10"/>
	<rect x="93.3" y="180" width="113.3" height="10"/>
	<rect x="93.3" y="113.3" width="113.3" height="10"/>
	<path d="M150,0C67,0,0,67,0,150c0,24.7,6,48,16.7,68.7L0,300l81.3-16.7C102,294,125.3,300,150,300c83,0,150-67,150-150S233,0,150,0
		z M150,290c-22.7,0-44-5.3-64-15.7l-3-1.7l-3.3,0.7L13,287l13.7-66.3l0.7-3.3l-1.7-3C15.4,194.1,10,172.7,10,150.1
		c0-77.3,62.7-140,140-140s140,62.7,140,140S227.3,290,150,290z"/>
</g>
</svg>
```
![스크린샷 2020-03-18 오전 1 53 58](https://user-images.githubusercontent.com/18350072/76880660-599f3300-68bb-11ea-8fbf-a6c9c0748dd9.png)

like upon image. this is nothing
Thanks to read. if find some error please let me know what is it. thanks

**Comment by kristerkari** [comment]
Hey @XOneto9. I think that the problem might be that your svg image does not have any width/height set, and then when you use 100% as width and height it might not scale it correctly.

Could you try to use for example `300` as width and height and try if it helps?

**Comment by XOneto9** [comment]
@kristerkari oh...
I got it 
Thanks I will try!

**Comment by XOneto9** [comment]
@kristerkari 
Thanks! It's work!
but one more thing, could I change the color of svg file ?

```
import ExampleImage from "../asssts/example.svg";

<ExampleImage width={100} height={30} fill={"#707070"} />
```

I was try to change color but, it doesn't work. 
should I do it?

**Comment by kristerkari** [comment]
> but one more thing, could I change the color of svg file ?

It works if you add a fill color to your SVG image and follow these instructions:
https://github.com/kristerkari/react-native-svg-transformer#changing-svg-fill-color-in-js-code
