### ISSUE TITLE
Color changing stopped working

### ISSUE THREAD

**Issue by schmru** [kristerkari/react-native-svg-transformer#81]
Hi, I need some help because of some weird bug, probably somewhere in my project.
I was coloring svg files with
{
  "replaceAttrValues": {
    "#000": "{props.stroke}"
  }
}
And from start it was working fine, only the #000 color was replaced and the strokes that were not defined stayed as the designer set them.
But now suddenly when I set stroke all strokes change, even those that are not defined.
Is there a way to do something like:
{
  "replaceAttrValues": {
    "#000": "currentColor"
  }
}
so that all #000 would be replaced with "currentColor" and the svg color would be set with color prop?
Because the problem is that if I don't set the stroke color the svg replaces #000 with none or something like that and the image is not seen.

So I tried with {
    "replaceAttrValues": {
    "#000": "'currentColor'"
}
}
 <SVGFILE  color={#555} />
and also:
{
    "replaceAttrValues": {
    "#000": "#555"
}
}
And the color does not change. Is there and until I don't set the stroke color, strokes don't have color. Is there anything else I should check. The only thing that currently works is to set "currentColor" all over the svg file.

**Comment by brianMxBm** [comment]
Did you end up figuring this out? My stroke color isn't changing either with my current setup.
