### ISSUE TITLE
Unable to use svg file as component in react native web

### ISSUE THREAD

**Issue by lakshmajim** [kristerkari/react-native-svg-transformer#83]
**Repository with reproducible scenario**: [Rn web svg](https://github.com/lakshmajim/test-rn-web)

Unable to import and use the svg static images in web, the same thing is working in mobile

Sample code Im using to render svg images
```
import Logo from "../../../imgs/address.svg";
<Logo />
```

I have added `@svgr/webpack` to my web package and added below rules to `config-override.js` file
```
  config.module.rules.concat([
    {
      test: /\.svg$/,
      exclude: /node_modules[/\\](?!react-native-vector-icons|react-native-safe-area-view)/,
      use: [
        {
          loader: "@svgr/webpack"
        }
      ]
    },
    {
      test: /\.(jpg|png|woff|woff2|eot|ttf|svg)$/,
      loader: "file-loader"
    }
  ]);
```
Error i'm receiving on web 
```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/address.265daad5.svg') is not a valid name.
```
Is there any problem in my configuration ?

**Comment by kristerkari** [comment]
Hmm... could it be that the `file-loader` is used instead of the `@svgr/webpack` loader?

**Comment by lakshmajim** [comment]
Tried removing the `file-loader`, got the same error.

**Comment by shubhamdeol** [comment]
@ananth-minions  what worked for you?
