### ISSUE TITLE
0.14.3 not show icon, tab bottom react-navigation color not working properly

### ISSUE THREAD

**Issue by dinhduongson** [kristerkari/react-native-svg-transformer#84]
When I down to 0.13.0 it works

**Comment by kristerkari** [comment]
Please paste example code so that I can debug the issue.

**Comment by dinhduongson** [comment]
https://github.com/react-native-community/react-native-svg
https://github.com/kristerkari/react-native-svg-transformer

import Logo from './logo.svg';
<Logo width={120} height={40} />

**Comment by dinhduongson** [comment]
<Logo width={120} height={40} />

**Comment by kristerkari** [comment]
could you please link the contents of the SVG image that you are importing

**Comment by dinhduongson** [comment]
any svg file I export from my xd file

**Comment by dinhduongson** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <defs>
    <style>
      .cls-1 {
        fill: #999;
      }
    </style>
  </defs>
  <g id="Group_16" data-name="Group 16" transform="translate(-470.91 -388.16)">
    <g id="Group_6" data-name="Group 6" transform="translate(470.91 388.16)">
      <path id="Path_7" data-name="Path 7" class="cls-1" d="M482.91,412.16a12,12,0,1,1,12-12A12.016,12.016,0,0,1,482.91,412.16Zm0-22a10,10,0,1,0,10,10A10.012,10.012,0,0,0,482.91,390.159Z" transform="translate(-470.91 -388.16)"/>
    </g>
    <g id="Group_8" data-name="Group 8" transform="translate(475.976 392.07)">
      <circle id="Ellipse_2" data-name="Ellipse 2" class="cls-1" cx="4.015" cy="4.015" r="4.015" transform="translate(2.919 0)"/>
      <g id="Group_7" data-name="Group 7" transform="translate(0 10.241)">
        <path id="Path_8" data-name="Path 8" class="cls-1" d="M489.454,427.131a8.908,8.908,0,0,0,6.934-3.308,9.051,9.051,0,0,0-13.868,0A8.922,8.922,0,0,0,489.454,427.131Z" transform="translate(-482.52 -420.59)"/>
      </g>
    </g>
  </g>
</svg>

**Comment by dinhduongson** [comment]
https://drive.google.com/file/d/19ByKydfzjqo-vQoSjq6sKxMMI0GnB4xc/view?usp=sharing

**Comment by kristerkari** [comment]
@dinhduongson I had a look at your image and tested it with both v0.14 and v0.13.

The reason why the color is different for those versions is because 0.13 did not have support for the `<style>` element inside SVG images. 0.14 adds support for that, so the grey color from the `<style>` tag gets applied. 

That means that everything is working correctly if you use 0.14.

**Comment by dinhduongson** [comment]
I use react-navigation, when i click to tab have user icon, it doesn't change color as 0.13

**Comment by kristerkari** [comment]
In that case you can try to remove the `<style>` tag from inside the SVG and see if that helps.
