### ISSUE TITLE
Expose some information of the SVG as properties

### ISSUE THREAD

**Issue by davazp** [kristerkari/react-native-svg-transformer#90]
It would be very convenient to expose some properties like viewBox as properties of the generated component.

Now we need to duplicate this information in our code even though (I think?) this plugin has access to it.

For instance, something like

```javascript
import Icon from './myIcon.svg'
Icon.viewBox
```

My use case is, I want to scale a SVG to fit the screen width, but without slicing it vertically, just letting it take the height it should take.

I do this currently by hardcoding viewBox in the code and computing the new height value myself.

If there are alternative ways to do this I'd like to hear as well.

Thanks!

**Comment by kristerkari** [comment]
Thanks, I understand what you problem is.

This library is using [SVGR](https://github.com/gregberge/svgr), so the API that it provides is the same. 

I'm not sure if I want to start building own things on top it, but I'm open for suggestions on how to solve your problem.

**Comment by davazp** [comment]
It makes sense. I think I could probably manage to do what I want with custom templates of svgr:

https://react-svgr.com/docs/custom-templates/

I can try to get some info of the icon and re-export it.  Thanks for the help!
