### ISSUE TITLE
Use with svg files vs xml strings

### ISSUE THREAD

**Issue by nelsonprsousa** [kristerkari/react-native-svg-transformer#91]
I was reading README of react-native-svg and couldn't figure out what are the pros and cons of using react-native-svg with svg files or with xml string.

For what I could understood, using with svg files we can get compile time conversion and cached transformations using react-native-svg-transformer library.

The pros and cons of using with XML strings I don't know, specially pros/const between these two options.

Can you guys please explain? When should we use svg files vs xml string?

Thank you 🚀

**Comment by kristerkari** [comment]
> For what I could understood, using with svg files we can get compile time conversion and cached transformations using react-native-svg-transformer library.

This is correct. I'm not sure if there is some kind of caching done when using xml strings, but there might possibly be a small runtime performance hit involved.

> The pros and cons of using with XML strings I don't know, specially pros/const between these two options.

I don't think that there is a huge difference with the two approaches, but having the images in files might make it easier to use the same images in other places, for example a Web app.

**Comment by nelsonprsousa** [comment]
Thanks @kristerkari 
You rock 🚀
