### ISSUE TITLE
I am getting blank when importing my SVG image

### ISSUE THREAD

**Issue by shareef-dweikat** [kristerkari/react-native-svg-transformer#94]
`import Contact from '../assets/images/contact.svg'

 < Image width={50} height={50} source={Contact}  />
`
i am using react-native-svg  and react-native-svg-transformer

**Comment by SimonRobert0** [comment]
Hi @shareef-dweikat 
Just do :

import Contact from '../assets/images/contact.svg'
<Contact style={{...}} />

it should work

**Comment by kristerkari** [comment]
@SimonRobert0 is correct, you are not supposed to use `Image`, but instead what you import, e.g. `<Contact width={50} height={50}>`
